# Generated by Django 5.1.1 on 2024-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender_user_kelas_user_nip_alter_user_nim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meeting_url', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
