# Generated by Django 5.1.1 on 2024-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pnaggilan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
