# Generated by Django 5.1.1 on 2024-09-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cheatdetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatdetection',
            name='user',
        ),
        migrations.AddField(
            model_name='cheatdetection',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
