# Generated by Django 5.1.1 on 2024-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_cheatdetection_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheatdetection',
            old_name='image',
            new_name='screenshot',
        ),
        migrations.RemoveField(
            model_name='cheatdetection',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='cheatdetection',
            name='kelas',
        ),
        migrations.AddField(
            model_name='cheatdetection',
            name='class_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cheatdetection',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
