# Generated by Django 5.1.1 on 2024-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_image_cheatdetection_screenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_name', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cheating_image', models.ImageField(upload_to='cheating_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='CheatDetection',
        ),
    ]
